---

version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "dependencies"
    assignees:
      - "Plaenkler"
    reviewers:
      - "Plaenkler"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "dependencies"
    assignees:
      - "Plaenkler"
    reviewers:
      - "Plaenkler"
