---

version: "2"
run:
  timeout: 60s

linters:
  default: all
  disable:
    - cyclop
    - exhaustive
    - exhaustruct
    - forbidigo
    - funlen
    - gochecknoglobals
    - godot
    - err113
    - lll
    - nakedret
    - nestif
    - godox
    - dupl
    - goconst
    - nilerr
    - ireturn
    - nosprintfhostport
    - depguard
    - rowserrcheck
    - sqlclosecheck
    - wastedassign
    - mnd
